name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: install and build
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -havz
          remote_host: ${{ secrets.SERVER_IP_ADDRESS }}
          remote_user: ${{ secrets.SERVER_USERNAME }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          remote_port: 22
          path: "build/"
          remote_path: "/srv/http/springstrap/"
